# Generated by Django 4.2.11 on 2024-04-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('diary_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('contents', models.CharField(max_length=500)),
                ('privacy', models.IntegerField(db_comment='1 == public\n0 == private\n')),
            ],
            options={
                'db_table': 'Diary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diaryhashtag',
            fields=[
                ('table_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'DiaryHashtag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('hashtag_id', models.AutoField(primary_key=True, serialize=False)),
                ('hashtag', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Hashtag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.IntegerField(primary_key=True, serialize=False)),
                ('file', models.TextField()),
            ],
            options={
                'db_table': 'Image',
                'managed': False,
            },
        ),
    ]
