# Generated by Django 4.2.11 on 2024-04-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=36)),
                ('bname', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('satisfaction', models.IntegerField()),
            ],
            options={
                'db_table': 'Expense',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('income_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=16)),
                ('date', models.DateTimeField()),
                ('memo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Income',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Withwhom',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'WithWhom',
                'managed': False,
            },
        ),
    ]
